import { StyleSheet } from "react-native";

export const comprehensiveRoof3dAssessmentStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  loadingText: { marginTop: 15, fontSize: 16, color: "#2196F3" },
  errorContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  errorText: { fontSize: 16, color: "#f44336", marginBottom: 15 },
  retryButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#2196F3",
    borderRadius: 5,
  },
  retryText: { color: "white", fontSize: 14, fontWeight: "bold" },
  mainTabBar: {
    flexDirection: "row",
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  mainTab: { flex: 1, paddingVertical: 12, alignItems: "center" },
  activeMainTab: { borderBottomWidth: 3, borderBottomColor: "#2196F3" },
  mainTabText: { fontSize: 14, color: "#999" },
  activeMainTabText: { color: "#2196F3", fontWeight: "bold" },
  tabContent: { flex: 1 },
  metaCard: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderLeftColor: "#2196F3",
  },
  metaAddress: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  metaCoords: { fontSize: 12, color: "#666" },
  reportContainer: { flex: 1, padding: 10 },
  summaryCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#333",
  },
  summaryGrid: { flexDirection: "row", justifyContent: "space-between" },
  summaryItem: { alignItems: "center" },
  summaryItemValue: { fontSize: 20, fontWeight: "bold", color: "#2196F3" },
  summaryItemLabel: { fontSize: 11, color: "#999", marginTop: 5 },
  complexityCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  complexityLabel: { fontSize: 14, color: "#666", marginBottom: 8 },
  complexityValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2196F3",
    marginBottom: 10,
  },
  complexityBar: {
    height: 8,
    backgroundColor: "#e0e0e0",
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 8,
  },
  complexityFill: { height: "100%", backgroundColor: "#2196F3" },
  complexityScore: { fontSize: 12, color: "#999", textAlign: "center" },
  section: { marginBottom: 15 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 12,
    color: "#333",
  },
  planeDetailCard: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: "#e0e0e0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  planeDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  planeBullet: { width: 12, height: 12, borderRadius: 2, marginRight: 10 },
  planeDetailTitle: {
    fontSize: 13,
    fontWeight: "bold",
    flex: 1,
    color: "#333",
  },
  planePitchBadge: {
    fontSize: 12,
    fontWeight: "bold",
    color: "white",
    backgroundColor: "#2196F3",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  planeMetrics: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  metricColumn: { flex: 1 },
  metricLabel: { fontSize: 11, color: "#999", marginBottom: 3 },
  metricValue: { fontSize: 12, fontWeight: "bold", color: "#333" },
  costBreakdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    marginBottom: 8,
  },
  costLabel: { fontSize: 12, color: "#666" },
  costValue: { fontSize: 12, fontWeight: "bold", color: "#4CAF50" },
  timeEstimate: { flexDirection: "row", justifyContent: "space-between" },
  timeLabel: { fontSize: 12, color: "#666" },
  timeValue: { fontSize: 12, fontWeight: "bold", color: "#FF9800" },
  recommendationItem: {
    flexDirection: "row",
    marginBottom: 10,
    backgroundColor: "white",
    padding: 12,
    borderRadius: 6,
  },
  recommendationBullet: { fontSize: 14, color: "#2196F3", marginRight: 10 },
  recommendationText: { flex: 1, fontSize: 12, color: "#666", lineHeight: 18 },
  featuresGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "white",
    borderRadius: 8,
    padding: 15,
  },
  featureItem: { alignItems: "center" },
  featureValue: { fontSize: 20, fontWeight: "bold", color: "#2196F3" },
  featureLabel: { fontSize: 11, color: "#999", marginTop: 5 },
  costSummaryCard: {
    backgroundColor: "#2196F3",
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  costSummaryTitle: {
    fontSize: 14,
    color: "rgba(255,255,255,0.9)",
    marginBottom: 10,
  },
  totalCost: {
    fontSize: 36,
    fontWeight: "bold",
    color: "white",
    marginBottom: 8,
  },
  costNote: { fontSize: 12, color: "rgba(255,255,255,0.8)" },
});
