import { StyleSheet } from "react-native";

export const gisBuildingMapScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  loadingText: { marginTop: 15, fontSize: 16, color: "#2196F3" },
  emptyContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  emptyText: { fontSize: 16, color: "#999", marginBottom: 15 },
  retryButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#2196F3",
    borderRadius: 5,
  },
  retryButtonText: { color: "white", fontSize: 14, fontWeight: "bold" },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  tab: { flex: 1, paddingVertical: 12, alignItems: "center" },
  activeTab: { borderBottomWidth: 3, borderBottomColor: "#2196F3" },
  tabText: { fontSize: 14, color: "#999" },
  activeTabText: { color: "#2196F3", fontWeight: "bold" },
  mapContainer: { flex: 1, minHeight: 280 },
  map: { flex: 1, minHeight: 280 },
  aerialContainer: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "white",
    borderRadius: 8,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  aerialImage: { width: 120, height: 80 },
  aerialLabel: { fontSize: 10, color: "#666", padding: 5, textAlign: "center" },
  detailsContainer: { flex: 1, padding: 10 },
  materialsContainer: { flex: 1, padding: 10 },
  card: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 12,
    color: "#333",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    paddingBottom: 8,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  label: { fontSize: 14, color: "#666", fontWeight: "600" },
  value: { fontSize: 14, color: "#2196F3", fontWeight: "bold" },
  complexityBar: {
    flex: 1,
    height: 8,
    backgroundColor: "#e0e0e0",
    borderRadius: 4,
    marginHorizontal: 10,
    overflow: "hidden",
  },
  complexityFill: {
    height: "100%",
    backgroundColor: "#2196F3",
    borderRadius: 4,
  },
  materialCard: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  materialHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: "#2196F3",
  },
  materialName: { fontSize: 16, fontWeight: "bold", color: "#333" },
  materialCost: { fontSize: 16, fontWeight: "bold", color: "#4CAF50" },
  materialInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  infoItem: { flex: 1 },
  infoLabel: { fontSize: 12, color: "#999", marginBottom: 3 },
  infoValue: { fontSize: 13, color: "#333", fontWeight: "600" },
  ratingContainer: { marginVertical: 12 },
  ratingItem: { marginVertical: 8 },
  ratingLabel: {
    fontSize: 12,
    color: "#666",
    marginBottom: 4,
    fontWeight: "600",
  },
  ratingBar: {
    height: 6,
    backgroundColor: "#e0e0e0",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 4,
  },
  ratingFill: { height: "100%", backgroundColor: "#2196F3" },
  ratingValue: { fontSize: 11, color: "#2196F3", fontWeight: "bold" },
  recommendation: {
    fontSize: 13,
    color: "#666",
    fontStyle: "italic",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
});
