import type { FormState } from "./measurementFormTypes";

/** Blank intake — address search and measurements start empty. */
export function defaultFormState(): FormState {
  return {
    address: "",
    stateCode: "",
    latitude: "",
    longitude: "",
    roofType: "Asphalt Shingle",
    roofStructure: "auto",
    stories: "",
    exteriorWallHeightFt: "",
    areaSqFt: "",
    perimeterFt: "",
    roofPitch: "6/12",
    wastePercent: "12",
    measuredSquares: "",
    ridgesFt: "",
    eavesFt: "",
    rakesFt: "",
    valleysFt: "",
    hipsFt: "",
    wallFlashingFt: "",
    stepFlashingFt: "",
    othersFt: "",
    severity: 2,
    damageTypes: [],
    estimateScopeMode: "replace",
    propertyRecordNotes: "",
    estimateAddonModBitDetailed: "",
    estimateAddonDryInSq: "",
    estimateAddonGutterLf: "",
    estimateAddonGcAllowanceUsd: "",
    estimateAddonCopperLf: "",
    estimateAddonFreightEa: "",
    estimateAddonEngineeringEa: "",
    estimateAddonSidingSf: "",
    estimateAddonWindowEa: "",
    estimateAddonTrimLf: "",
    estimateAddonTileLoadSq: "",
    estimateAddonTileInstallSq: "",
  };
}
