CREATE TABLE `callTracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`callSid` varchar(100) NOT NULL,
	`direction` enum('inbound','outbound') NOT NULL,
	`fromNumber` varchar(20) NOT NULL,
	`toNumber` varchar(20) NOT NULL,
	`status` varchar(50),
	`duration` int,
	`recordingUrl` varchar(500),
	`transcription` text,
	`leadId` int,
	`callbackRequestId` int,
	`source` varchar(100),
	`outcome` enum('connected','voicemail','no_answer','busy','failed'),
	`followUpRequired` boolean DEFAULT false,
	`startedAt` timestamp,
	`endedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `callTracking_id` PRIMARY KEY(`id`),
	CONSTRAINT `callTracking_callSid_unique` UNIQUE(`callSid`)
);
--> statement-breakpoint
CREATE TABLE `callbackRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`userProfileId` int,
	`name` varchar(255) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`email` varchar(320),
	`preferredTime` varchar(100),
	`preferredDate` date,
	`timezone` varchar(50) DEFAULT 'America/Chicago',
	`requestReason` text,
	`urgency` enum('low','medium','high','emergency') DEFAULT 'medium',
	`conversationContext` text,
	`status` enum('pending','scheduled','completed','cancelled','no_answer') DEFAULT 'pending',
	`scheduledFor` timestamp,
	`completedAt` timestamp,
	`assignedTo` varchar(255),
	`callSid` varchar(100),
	`callDuration` int,
	`callRecordingUrl` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `callbackRequests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `smsOptIns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`phone` varchar(20) NOT NULL,
	`name` varchar(255),
	`email` varchar(320),
	`optedIn` boolean NOT NULL DEFAULT true,
	`optInSource` varchar(100),
	`optInDate` timestamp NOT NULL DEFAULT (now()),
	`optOutDate` timestamp,
	`messageTypes` text,
	`frequency` enum('all','important_only','weekly_digest') DEFAULT 'all',
	`leadId` int,
	`userProfileId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `smsOptIns_id` PRIMARY KEY(`id`),
	CONSTRAINT `smsOptIns_phone_unique` UNIQUE(`phone`)
);
